sudo: false
language: go

go:
- "1.11.2"

script:
- make dev-deps
- make deps build

before_deploy:
- test "$TRAVIS_PULL_REQUEST" == "false" && test -n "$TRAVIS_TAG" && make dist
- sha256sum aws-secret_* > sha256sum.txt

deploy:
  provider: releases
  api_key:
    secure: Jvblobd26f3VVzvWXKhOBhkCk9Dx1qTDgajyMugy4CqMirOnw/2yKLyoRdwuS/V7QGAtIr/S/AMPNZxuihdIhTpiqZVZjYaSZHRYrlOFzEBAlvQkvH6g6Huzt9PwZMQMTdEYudr9LTe1mkk7IRe1XxGxHALmvxrnVYxpPlpNR0LK1hNsWsLQtBLKea0BiGuFxZ2uOvz3mNzJPc4fKecQGCTFedkv1gv2QJtnYYlDtugG2HqQnJhj4xHDJ0ki2FuhjdIewmbjRJWDrzn+pUP40pf5hlWWzZtjXfWlicWD+cGOhfK+LC9/VGC6xFEwQGyA7Tpb4Ml+8vnP5RWFcU0/FuChshXXVEJmQTkL8kzY7fmMbnokwHbcV7s/j3jnIvo51gRSiXgDYUvfVFuLjC6p5/3P2NySO57XQIR035j+81NAAff2VAi3MQBomsrED2M1qHGQ0ynI6FHFKXMPqbBAgE7Cp6UwQXalDdb4yEDUdgcve0y7K/je7NWBvnPFfqYZoIIbF0BHdW2hNly00XFBMUfMnlhSloqQi3GBXfyLr+adHYFNWU7EBpucp6hvRasuQ8JJeSFkuI1DNmDpABHRIu7sc+SHAaLOsWJEJ2LDLHqjM1dso4u+knPYvx76RrQNd3k1oO2uqX4Z82yCKQnUx52MZKQOKpfMdVsM/sB6H9Y=
  file:
  - aws-secret_darwin_amd64
  - aws-secret_linux_amd64
  - sha256sum.txt
  skip_cleanup: true
  on:
    repo: troykinsella/aws-secret
    tags: true
    go: "1.11.2"
